name: ao_bi
description: Validate Angolan Identity Card
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.3
  flutter: ">=1.17.0"

dependencies:
  qr_code_scanner: ^0.7.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
